# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
#- repo: self
#  containers:
#  - container: linux
#    image: dockerazure.azurecr.io/cimage:439
#    type: ACR
#    endpoint: dockerazure
#    subscription: 7489b9b9-8abe-4b02-a0d9-f09f368df55f 
#    registry: dockerazure

variables:
  # Container registry service connection established during pipeline creation
  #dockerRegistryServiceConnection: '0e17cdb1-fb53-4f4b-b64a-8c76b58bd9f4'
  imageRepository: 'cimage'
  containerRegistry: 'dockerazure.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  containerPath: '/app/test/TestResults'
  imgName: '$(containerRegistry)/$(imageRepository):$(tag)'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

pool:
      vmImage: $(vmImageName)

container:
  image: dockerazure.azurecr.io/cimage:439
  endpoint: dockerazure

steps:
- script: |
      mkdir TestResults
      docker run --rm -v $(System.DefaultWorkingDirectory)/TestResults:$(containerPath) $(imgName)
  continueOnError: true
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '*.trx'
    searchFolder: '$(System.DefaultWorkingDirectory)/TestResults'


   
